name: Build Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-base:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        desktop: ["kde", "mate", "xfce"]
        base: ["base"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'new-gen'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the ${{ matrix.base }} ${{ matrix.desktop }} image
        run: docker compose -f builds/${{ matrix.base }}.yml --env-file builds/env/${{ matrix.desktop }}.env build

  build-plugins:
    needs: build-base
    strategy:
      matrix:
        os: [ubuntu-latest]
        desktop: ["kde", "mate", "xfce"]
        plugin: ["NAV_19HIPA", "NAV_20HIPA", "NAV_21HIPA", "NAV_22HIPAK", "NAV_IGAZOL", "OEP_egt_tagallam", "OEP_igenylolap_eu_kartyahoz"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'new-gen'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the ${{ matrix.plugin }} ${{ matrix.desktop }} image
        run: docker compose -f builds/plugin/${{ matrix.plugin }}.yml --env-file builds/env/${{ matrix.desktop }}.env build
